#version: 2
#updates:
#  - package-ecosystem: "pip"
#    directory: "/"
#    schedule:
#      interval: "monthly"
#      day: "friday"
#
#  # Updates the dependencies of the GitHub Actions workflows
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "monthly"
#      day: "friday"
