# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the additional_dependencies here match requirements.txt
repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
      - id: black
        args:
            - --diff
            - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
    -   id: pylint
        args:
            - --rcfile=setup.cfg
        additional_dependencies:
            - python-telegram-bot==13.4.1
            - Sphinx==3.5.4
            - rapidfuzz==1.4.1
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        additional_dependencies:
            - python-telegram-bot==13.4.1
            - Sphinx==3.5.4
            - rapidfuzz==1.4.1
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.13.0
    hooks:
    -   id: pyupgrade
        args:
          - --py36-plus